#ifndef TYPES_H
#define TYPES_H

enum Colour{WHITE, BLACK};

enum PlayerType {HUMAN, COMPUTER1, COMPUTER2, COMPUTER3, COMPUTER4};

enum CommandType {STARTGAME, RESIGN, MOVE, SETUP, ADDPIECE, REMOVEPIECE, SETCOLOUR, DONESETUP};

#endif